# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - feature-*
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Get branch name
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Install aws-iam-authenticator
      uses: prepor/action-aws-iam-authenticator@master
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: a11y-cat
        IMAGE_TAG: ${{ steps.vars.outputs.short_ref }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Install kubectl, helm and deploy app
      run: |
        echo "Installing kubectl"
        curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.7/2020-07-08/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/bin/kubectl
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > /tmp/config
        export KUBECONFIG=/tmp/config
        kubectl version --short --client
        kubectl get svc
        echo "installing helm"
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
        echo "deploying app via helm"
        helm upgrade a11y-cat-${{ steps.vars.outputs.short_ref }} ./a11y-cat --install --namespace=a11y-cat --set=image.tag=${{ steps.vars.outputs.short_ref }}
        echo "get the deployed url"
        kubectl get ingress/a11y-cat-${{ steps.vars.outputs.short_ref }}-ingress -n a11y-cat